export type {
  NewMaintenanceTypeKey,
  NewMaintenancePriority,
  MaintenanceOriginKey,
  OperationalStatusKey,
  DiagnosisAreaKey,
  DiagnosisAreaStatus,
  DiagnosisAreaState,
  MaintenanceKartOption,
  PredictedPartLine,
  PlannedServiceKey,
  SmartAlert,
  AffectedBooking,
  ItemSeverity,
} from "@/lib/admin-new-maintenance-mocks";
