/** Tipos da área do aluno — dados via StudentAreaServiceMock / TelemetryServiceMock */
export type {
  NavItemKey,
  EvolutionLapPoint,
  TimelineItem,
  DevTabKey,
  DevCheckItem,
  DevelopmentTabPayload,
  TelemetryPilotSession,
  TelemetrySectorRow,
  TelemetryDeviceType,
  TelemetryTabKey,
  TelemetrySessionLap,
  Achievement,
  AchievementCategory,
  ACHIEVEMENT_CATEGORY_META,
  TrainingLapDetail,
  ResultRow,
  VideoMaterial,
  QuickAction,
} from "@/lib/student-area-mocks";
