import { SettingsRepositoryMock } from "@/repositories/settings/SettingsRepositoryMock";

export const SettingsServiceMock = {
  getTabs: () => SettingsRepositoryMock.getTabs(),
  getGeneralSettings: () => SettingsRepositoryMock.getGeneralSettings(),
  getPermissionLabels: () => SettingsRepositoryMock.getPermissionLabels(),
  getRoles: () => SettingsRepositoryMock.getRoles(),
  getWeekSchedule: () => SettingsRepositoryMock.getWeekSchedule(),
  getSpecificDateSchedules: () => SettingsRepositoryMock.getSpecificDateSchedules(),
  getScheduleExceptions: () => SettingsRepositoryMock.getScheduleExceptions(),
  getPlanCategories: () => SettingsRepositoryMock.getPlanCategories(),
  getKartCategories: () => SettingsRepositoryMock.getKartCategories(),
  getSkillLevels: () => SettingsRepositoryMock.getSkillLevels(),
  getWeekDayKeyFromDate: SettingsRepositoryMock.getWeekDayKeyFromDate,
  getEffectiveScheduleSlotsForDate:
    SettingsRepositoryMock.getEffectiveScheduleSlotsForDate,
  scheduleSlotDurationMinutes: SettingsRepositoryMock.scheduleSlotDurationMinutes,
  formatScheduleDuration: SettingsRepositoryMock.formatScheduleDuration,
  findScheduleSlot: SettingsRepositoryMock.findScheduleSlot,
  createTimeSlot: SettingsRepositoryMock.createTimeSlot,
  createSpecificDateSchedule: SettingsRepositoryMock.createSpecificDateSchedule,
  createSpecificDateTimeSlot: SettingsRepositoryMock.createSpecificDateTimeSlot,
  createScheduleException: SettingsRepositoryMock.createScheduleException,
  createDefaultPlans: SettingsRepositoryMock.createDefaultPlans,
  createEmptyPlan: SettingsRepositoryMock.createEmptyPlan,
  createKartCategory: SettingsRepositoryMock.createKartCategory,
  syncPlanCategoriesFromKart: SettingsRepositoryMock.syncPlanCategoriesFromKart,
  syncLevelRequirements: SettingsRepositoryMock.syncLevelRequirements,
  getSettingsKarts: () => SettingsRepositoryMock.getSettingsKarts(),
  getSettingsKartStatuses: () => SettingsRepositoryMock.getSettingsKartStatuses(),
  getFeedbackCriteria: () => SettingsRepositoryMock.getFeedbackCriteria(),
  getNotificationChannels: () => SettingsRepositoryMock.getNotificationChannels(),
  getNotificationEvents: () => SettingsRepositoryMock.getNotificationEvents(),
  getIntegrations: () => SettingsRepositoryMock.getIntegrations(),
  getSecurityCards: () => SettingsRepositoryMock.getSecurityCards(),
  getAppearanceSettings: () => SettingsRepositoryMock.getAppearanceSettings(),
  getRankingSettings: () => SettingsRepositoryMock.getRankingSettings(),
  getDocumentTemplates: () => SettingsRepositoryMock.getDocumentTemplates(),
  getAuditLog: () => SettingsRepositoryMock.getAuditLog(),
  createSettingsKart: SettingsRepositoryMock.createSettingsKart,
  nextSettingsKartNumber: SettingsRepositoryMock.nextSettingsKartNumber,
};
