import * as inventoryMocks from "@/lib/admin-inventory-mocks";

export const InventoryCatalogRepositoryMock = {
  getTabs: () => inventoryMocks.INVENTORY_TABS,
  getTabMeta: () => inventoryMocks.INVENTORY_TAB_META,
  getTablePageSizes: () => inventoryMocks.INVENTORY_TABLE_PAGE_SIZES,
  getStockHealthFilterOptions: () => inventoryMocks.STOCK_HEALTH_FILTER_OPTIONS,
  getCategories: () => inventoryMocks.INVENTORY_CATEGORIES,
  getKpis: () => inventoryMocks.INVENTORY_KPIS,
  getStaticParts: () => inventoryMocks.INVENTORY_PARTS,
  getMovements: () => inventoryMocks.INVENTORY_MOVEMENTS,
  getMovementTypeLabels: () => inventoryMocks.MOVEMENT_TYPE_LABELS,
  getPurchaseOrders: () => inventoryMocks.PURCHASE_ORDERS,
  getPurchaseStatusLabels: () => inventoryMocks.PURCHASE_STATUS_LABELS,
  getCriticalStock: () => inventoryMocks.CRITICAL_STOCK,
  getNfReferences: () => inventoryMocks.INVENTORY_NF_REFERENCES,
  getStaticSuppliers: () => inventoryMocks.INVENTORY_SUPPLIERS,
  getSupplierStatusLabels: () => inventoryMocks.SUPPLIER_STATUS_LABELS,
  getAlerts: () => inventoryMocks.INVENTORY_ALERTS,
  getHistory: () => inventoryMocks.INVENTORY_HISTORY,
  getPartDetail: inventoryMocks.getPartDetail,
  getWeeklyConsumption: () => inventoryMocks.WEEKLY_CONSUMPTION,
  getConsumptionByCategory: () => inventoryMocks.CONSUMPTION_BY_CATEGORY,
  getTopUsedParts: () => inventoryMocks.TOP_USED_PARTS,
  getMonthlyMovements: () => inventoryMocks.MONTHLY_MOVEMENTS,
  getCostByCategory: () => inventoryMocks.COST_BY_CATEGORY,
  getFinancialIntegration: () => inventoryMocks.FINANCIAL_INTEGRATION,
  getSupplierNames: () => inventoryMocks.SUPPLIER_NAMES,
  getLocations: () => inventoryMocks.LOCATIONS,
  filterPartsList: inventoryMocks.filterPartsList,
  filterParts: inventoryMocks.filterParts,
  filterSuppliersList: inventoryMocks.filterSuppliersList,
  filterSuppliers: inventoryMocks.filterSuppliers,
  formatInventoryDate: inventoryMocks.formatInventoryDate,
  formatCurrency: inventoryMocks.formatCurrency,
};
