export type {
  SettingsTabKey,
  GeneralSettingsForm,
  PermissionKey,
  RolePermissions,
  RoleKey,
  ModuleKey,
  ModuleGroupKey,
  ModulePermissionSet,
  SettingsUserAccount,
  ScheduleTimeSlot,
  WeekDayKey,
  WeekDaySchedule,
  SpecificDateSchedule,
  ScheduleException,
  CategoryPrice,
  KartCategory,
  LevelCategoryRequirement,
  SkillLevel,
  SettingsKartRow,
  FeedbackCriterion,
  NotificationChannel,
  NotificationEvent,
  IntegrationItem,
  DocumentTemplate,
  AuditEntry,
} from "@/lib/admin-settings-mocks";

export { MODULE_LABELS, MODULE_GROUPS } from "@/lib/admin-settings-mocks";
