import * as mocks from "@/lib/student-area-mocks";

export const StudentAreaRepositoryMock = {
  getStudentNav: () => mocks.STUDENT_NAV,
  getStudentNavHref: () => mocks.STUDENT_NAV_HREF,
  getStudentProfile: () => mocks.STUDENT_PROFILE,
  getNextClass: () => mocks.NEXT_CLASS,
  getHeroLevel: () => mocks.HERO_LEVEL,
  getEvolutionLapSeries: () => mocks.EVOLUTION_LAP_SERIES,
  getEvolutionGoal: () => mocks.EVOLUTION_GOAL,
  getKpiMetrics: () => mocks.KPI_METRICS,
  getNextActivities: () => mocks.NEXT_ACTIVITIES,
  getFeedback: () => mocks.FEEDBACK,
  getDevelopmentTabs: () => mocks.DEVELOPMENT_TABS,
  getDevelopmentByTab: () => mocks.DEVELOPMENT_BY_TAB,
  getAchievements: () => mocks.ACHIEVEMENTS,
  getLastResults: () => mocks.LAST_RESULTS,
  getVideoMaterials: () => mocks.VIDEO_MATERIALS,
  getQuickActions: () => mocks.QUICK_ACTIONS,
  getSidebarPlan: () => mocks.SIDEBAR_PLAN,
  getSidebarCompete: () => mocks.SIDEBAR_COMPETE,
  getTelemetryStats: () => mocks.TELEMETRY_STATS,
  getTelemetryPilotSessions: () => mocks.TELEMETRY_PILOT_SESSIONS,
  getTelemetryDefaultSessionId: () => mocks.TELEMETRY_DEFAULT_SESSION_ID,
  getTelemetrySectorsBySession: () => mocks.TELEMETRY_SECTORS_BY_SESSION,
  getTelemetryDeviceOptions: () => mocks.TELEMETRY_DEVICE_OPTIONS,
  getTelemetryChartMetrics: () => mocks.TELEMETRY_CHART_METRICS,
  getTelemetryTabs: () => mocks.TELEMETRY_TABS,
  getTelemetryLapColors: () => mocks.TELEMETRY_LAP_COLORS,
  getTelemetryChartGroup: () => mocks.TELEMETRY_CHART_GROUP,
  getTelemetryTrackMap: () => mocks.TELEMETRY_TRACK_MAP,
  getTelemetryTrackLengthM: () => mocks.TELEMETRY_TRACK_LENGTH_M,
  getTelemetryDistanceM: () => mocks.TELEMETRY_DISTANCE_M,
  getTelemetryYAxis: () => mocks.TELEMETRY_Y_AXIS,
  getTelemetryChartByTab: () => mocks.TELEMETRY_CHART_BY_TAB,
  getTelemetrySessionLaps: () => mocks.TELEMETRY_SESSION_LAPS,
  getTelemetrySectorsForSession: mocks.getTelemetrySectorsForSession,
  getTelemetryPilotSession: mocks.getTelemetryPilotSession,
  telemetrySeriesForLap: mocks.telemetrySeriesForLap,
  telemetryLapSeries: mocks.telemetryLapSeries,
  telemetryYExtentForLaps: mocks.telemetryYExtentForLaps,
  telemetrySharedYExtent: mocks.telemetrySharedYExtent,
};
