import * as settingsMocks from "@/lib/admin-settings-mocks";
import * as termsMocks from "@/lib/admin-settings-terms-mocks";

export const SettingsRepositoryMock = {
  getTabs: () => settingsMocks.SETTINGS_TABS,
  getGeneralSettings: () => settingsMocks.GENERAL_SETTINGS,
  getPermissionLabels: () => settingsMocks.PERMISSION_LABELS,
  getRoles: () => settingsMocks.ROLES,
  getWeekSchedule: () => settingsMocks.WEEK_SCHEDULE,
  getSpecificDateSchedules: () => settingsMocks.SPECIFIC_DATE_SCHEDULES,
  getScheduleExceptions: () => settingsMocks.SCHEDULE_EXCEPTIONS,
  getCategoryPrices: () => settingsMocks.CATEGORY_PRICES,
  getSettingsUsers: () => settingsMocks.SETTINGS_USERS,
  getKartCategories: () => settingsMocks.KART_CATEGORIES,
  getSkillLevels: () => settingsMocks.SKILL_LEVELS,
  getWeekDayKeyFromDate: settingsMocks.getWeekDayKeyFromDate,
  getEffectiveScheduleSlotsForDate: settingsMocks.getEffectiveScheduleSlotsForDate,
  scheduleSlotDurationMinutes: settingsMocks.scheduleSlotDurationMinutes,
  formatScheduleDuration: settingsMocks.formatScheduleDuration,
  findScheduleSlot: settingsMocks.findScheduleSlot,
  createTimeSlot: settingsMocks.createTimeSlot,
  createSpecificDateSchedule: settingsMocks.createSpecificDateSchedule,
  createSpecificDateTimeSlot: settingsMocks.createSpecificDateTimeSlot,
  createScheduleException: settingsMocks.createScheduleException,
  createKartCategory: settingsMocks.createKartCategory,
  createSettingsUser: settingsMocks.createSettingsUser,
  syncCategoryPricesFromKart: settingsMocks.syncCategoryPricesFromKart,
  syncLevelRequirements: settingsMocks.syncLevelRequirements,
  getSettingsKarts: () => settingsMocks.SETTINGS_KARTS,
  getSettingsKartStatuses: () => settingsMocks.SETTINGS_KART_STATUSES,
  getFeedbackCriteria: () => settingsMocks.FEEDBACK_CRITERIA,
  getNotificationChannels: () => settingsMocks.NOTIFICATION_CHANNELS,
  getNotificationEvents: () => settingsMocks.NOTIFICATION_EVENTS,
  getIntegrations: () => settingsMocks.INTEGRATIONS,
  getSecurityCards: () => settingsMocks.SECURITY_CARDS,
  getAppearanceSettings: () => settingsMocks.APPEARANCE_SETTINGS,
  getRankingSettings: () => settingsMocks.RANKING_SETTINGS,
  getDocumentTemplates: () => settingsMocks.DOCUMENT_TEMPLATES,
  getAuditLog: () => settingsMocks.AUDIT_LOG,
  createSettingsKart: settingsMocks.createSettingsKart,
  nextSettingsKartNumber: settingsMocks.nextSettingsKartNumber,
  getTermsRegistry: () => termsMocks.SETTINGS_TERMS_REGISTRY,
  getDreAccounts: () => termsMocks.DRE_ACCOUNT_TERMS,
  getFinancialCategories: () => termsMocks.FINANCIAL_CATEGORY_TERMS,
  getInventoryPartCategories: () => termsMocks.INVENTORY_PART_CATEGORY_TERMS,
  getRegisteredMotorTerms: () => termsMocks.REGISTERED_MOTOR_TERMS,
  getRegisteredChassisTerms: () => termsMocks.REGISTERED_CHASSIS_TERMS,
  createDreAccountLine: termsMocks.createDreAccountLine,
  buildDreSections: termsMocks.buildDreSections,
  insertDreLineInGroup: termsMocks.insertDreLineInGroup,
  createFinancialCategory: termsMocks.createFinancialCategory,
  createInventoryPartCategory: termsMocks.createInventoryPartCategory,
  createRegisteredMotor: termsMocks.createRegisteredMotor,
  createRegisteredChassis: termsMocks.createRegisteredChassis,
  dreAccountKindLabel: termsMocks.dreAccountKindLabel,
};
