import * as settingsMocks from "@/lib/admin-settings-mocks";

export const SettingsRepositoryMock = {
  getTabs: () => settingsMocks.SETTINGS_TABS,
  getGeneralSettings: () => settingsMocks.GENERAL_SETTINGS,
  getPermissionLabels: () => settingsMocks.PERMISSION_LABELS,
  getRoles: () => settingsMocks.ROLES,
  getWeekSchedule: () => settingsMocks.WEEK_SCHEDULE,
  getSpecificDateSchedules: () => settingsMocks.SPECIFIC_DATE_SCHEDULES,
  getScheduleExceptions: () => settingsMocks.SCHEDULE_EXCEPTIONS,
  getPlanCategories: () => settingsMocks.PLAN_CATEGORIES,
  getKartCategories: () => settingsMocks.KART_CATEGORIES,
  getSkillLevels: () => settingsMocks.SKILL_LEVELS,
  getWeekDayKeyFromDate: settingsMocks.getWeekDayKeyFromDate,
  getEffectiveScheduleSlotsForDate: settingsMocks.getEffectiveScheduleSlotsForDate,
  scheduleSlotDurationMinutes: settingsMocks.scheduleSlotDurationMinutes,
  formatScheduleDuration: settingsMocks.formatScheduleDuration,
  findScheduleSlot: settingsMocks.findScheduleSlot,
  createTimeSlot: settingsMocks.createTimeSlot,
  createSpecificDateSchedule: settingsMocks.createSpecificDateSchedule,
  createSpecificDateTimeSlot: settingsMocks.createSpecificDateTimeSlot,
  createScheduleException: settingsMocks.createScheduleException,
  createDefaultPlans: settingsMocks.createDefaultPlans,
  createEmptyPlan: settingsMocks.createEmptyPlan,
  createKartCategory: settingsMocks.createKartCategory,
  syncPlanCategoriesFromKart: settingsMocks.syncPlanCategoriesFromKart,
  syncLevelRequirements: settingsMocks.syncLevelRequirements,
  getSettingsKarts: () => settingsMocks.SETTINGS_KARTS,
  getSettingsKartStatuses: () => settingsMocks.SETTINGS_KART_STATUSES,
  getFeedbackCriteria: () => settingsMocks.FEEDBACK_CRITERIA,
  getNotificationChannels: () => settingsMocks.NOTIFICATION_CHANNELS,
  getNotificationEvents: () => settingsMocks.NOTIFICATION_EVENTS,
  getIntegrations: () => settingsMocks.INTEGRATIONS,
  getSecurityCards: () => settingsMocks.SECURITY_CARDS,
  getAppearanceSettings: () => settingsMocks.APPEARANCE_SETTINGS,
  getRankingSettings: () => settingsMocks.RANKING_SETTINGS,
  getDocumentTemplates: () => settingsMocks.DOCUMENT_TEMPLATES,
  getAuditLog: () => settingsMocks.AUDIT_LOG,
  createSettingsKart: settingsMocks.createSettingsKart,
  nextSettingsKartNumber: settingsMocks.nextSettingsKartNumber,
};
